name: CI
on:  
  pull_request:
    branches: [Develop]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node js
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run format
      - run: npm run format:check
      - run: npm run test -- --coverage
        env:
          CI: true     
